### ISSUE TITLE
RedisConfigurationOptions.cs filename-classname difference

### ISSUE THREAD

**Issue by k-antonius** [garywoodfine/redis-mvc-core#1]
Is there is a reason the `RedisConfiguration` class is named differently from the `RedisConfigurationOptions.cs` filename? Just curious as to your rationale.

-- Thanks

**Comment by garywoodfine** [comment]
No rational other than its a demo project and I never really refactored it and worried about naming conventions etc

**Comment by k-antonius** [comment]
Got it. I wasn't sure if it was a convention of some kind for `ConfigurationOptions` objects. Thanks for the quick reply.
